# fly.toml app configuration file for Blowin' Cold AC
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blowincoldac"
primary_region = "dfw"

[build]
  [build.args]
    NGINX_VERSION = "1.25.3"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[env]
  SERVER_NAME = "blowincoldac.fly.dev"